[tool.pyright]
include = [""]

reportMissingImports = true
reportMissingTypeStubs = false
reportGeneralTypeIssues = true
reportOptionalMemberAccess = true
reportOptionalSubscript = true

pythonVersion = "3.11"
pythonPlatform = "Windows"

[tool.pytest.ini_options]
log_cli=true
log_level="INFO"
pythonpath = [
  ""
]